runtime: nodejs20

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: production
  MCP_MODE: remote
  PORT: 8080
  SFCC_API_BASE: "${SFCC_API_BASE}"
  SFCC_ADMIN_CLIENT_ID: "${SFCC_ADMIN_CLIENT_ID}"
  SFCC_ADMIN_CLIENT_SECRET: "${SFCC_ADMIN_CLIENT_SECRET}"

# Health checks
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Resource allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Network settings
network:
  session_affinity: false

# Handlers for static files and routing
handlers:
- url: /health
  script: auto
  secure: optional

- url: /.*
  script: auto
  secure: optional
